using System.Security.Cryptography;

/// <summary>How a missing secret is generated on first run.</summary>
public enum SecretKind
{
    /// <summary>32 alphanumeric characters.</summary>
    Password,
    /// <summary>64 alphanumeric characters (Phoenix / Rails secret_key_base).</summary>
    LongPassword,
    /// <summary>32 random bytes as 64 lowercase hex characters (openssl rand -hex 32).</summary>
    Hex32,
    /// <summary>16 random bytes as 32 lowercase hex characters (openssl rand -hex 16).</summary>
    Hex16,
    /// <summary>48 random bytes as base64 (openssl rand -base64 48).</summary>
    Base64,
    /// <summary>Laravel APP_KEY: "base64:" + 32 random bytes.</summary>
    LaravelKey,
    /// <summary>Never generated: must be provided in .env (tokens issued by another system).</summary>
    Manual,
}

/// <summary>
/// Every secret is an Aspire parameter named after its .env key (KUTT_DB_PASSWORD -> kutt-db-password),
/// so publish emits <c>${KUTT_DB_PASSWORD}</c> instead of the value.
/// Value lookup: .env key, legacy aliases, legacy init-container file, then (run mode only) a generated value
/// that is appended to .env so it survives restarts and is visible in one place.
/// </summary>
public sealed class LabSecrets(IDistributedApplicationBuilder builder)
{
    private readonly string envFile = Path.Combine(builder.AppHostDirectory, ".env");
    private readonly Dictionary<string, IResourceBuilder<ParameterResource>> parameters = new(StringComparer.Ordinal);

    public IResourceBuilder<ParameterResource> Get(string key, SecretKind kind = SecretKind.Password, string? legacyFile = null, params string[] aliases)
    {
        if (parameters.TryGetValue(key, out var existing))
        {
            return existing;
        }

        var name = key.ToLowerInvariant().Replace('_', '-');
        var value = Read(key);
        if (value is null)
        {
            value = aliases.Select(Read).FirstOrDefault(v => v is not null)
                ?? ReadLegacyFile(legacyFile)
                ?? (kind != SecretKind.Manual && builder.ExecutionContext.IsRunMode ? Generate(kind) : null);
            if (value is not null && builder.ExecutionContext.IsRunMode)
            {
                Persist(key, value);
            }
        }

        if (value is not null)
        {
            builder.Configuration[$"Parameters:{name}"] = value;
        }

        var parameter = builder.AddParameter(name, secret: true)
            .WithDescription(kind == SecretKind.Manual ? $".env `{key}` (required, set manually)" : $".env `{key}`");
        parameters.Add(key, parameter);
        return parameter;
    }

    private string? Read(string key) => builder.Configuration[key] is { Length: > 0 } value ? value : null;

    private static string? ReadLegacyFile(string? path)
    {
        if (path is null || !File.Exists(path))
        {
            return null;
        }
        try
        {
            return File.ReadAllText(path).Trim() is { Length: > 0 } value ? value : null;
        }
        catch (UnauthorizedAccessException)
        {
            // Legacy files are written by containers running as their own UID (e.g. synapse UID 991).
            // The AppHost runs as the host user and cannot always read them. Treat as missing: a new
            // value is generated, written to .env via Persist, and the container overwrites its copy.
            return null;
        }
        catch (IOException)
        {
            // Same: a transient I/O error on a legacy file must not crash the AppHost.
            return null;
        }
    }

    /// <summary>Fill an existing empty <c>KEY=</c> line in place (keeps .env sections intact), else append.</summary>
    private void Persist(string key, string value)
    {
        var lines = File.Exists(envFile) ? File.ReadAllLines(envFile).ToList() : [];
        var empty = lines.FindIndex(line => line.Trim() == $"{key}=");
        if (empty >= 0)
        {
            lines[empty] = $"{key}={value}";
        }
        else
        {
            if (!lines.Contains(GeneratedHeader)) lines.AddRange(["", GeneratedHeader]);
            lines.Add($"{key}={value}");
        }
        File.WriteAllText(envFile, string.Join('\n', lines) + "\n");
    }

    private const string GeneratedHeader = "## ===== Generated by apphost on first run (move into the right section if you like) =====";

    private static string Generate(SecretKind kind) => kind switch
    {
        SecretKind.Password => RandomAlphanumeric(32),
        SecretKind.LongPassword => RandomAlphanumeric(64),
        SecretKind.Hex32 => Convert.ToHexStringLower(RandomNumberGenerator.GetBytes(32)),
        SecretKind.Hex16 => Convert.ToHexStringLower(RandomNumberGenerator.GetBytes(16)),
        SecretKind.Base64 => Convert.ToBase64String(RandomNumberGenerator.GetBytes(48)),
        SecretKind.LaravelKey => "base64:" + Convert.ToBase64String(RandomNumberGenerator.GetBytes(32)),
        _ => throw new ArgumentOutOfRangeException(nameof(kind)),
    };

    private static string RandomAlphanumeric(int length) =>
        RandomNumberGenerator.GetString("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789", length);
}
